services:
  api:
    build: .
    container_name: gedpro-api
    ports:
      - "3001:3000"
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MONGODB_URI=mongodb://db_mongo:27017/${POSTGRES_DB}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    depends_on:
      - db_postgres
      - db_mongo
      - minio

  db_postgres:
    image: postgres:15-alpine
    container_name: gedpro-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  db_mongo:
    image: mongo:latest
    container_name: gedpro-mongo
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    container_name: gedpro-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"